#!/usr/bin/env bash
# This script displays "Holberton School" 10 times and says "Hi" during the 9th

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Holberton School"
  (( count++ ))
done
